name: checkout 
on: workflow_dispatch

jobs:
    no-checkout:
        runs-on: ubuntu-latest
        steps:
        - name: checkout file list
          run: cat README.md # 레포지토리 파일을 읽지 못해서 오류 발생! 
    
    checkout:
        runs-on: ubuntu-latest
        steps:
        - name: use checkout action
          uses: actions/checkout@v4
        - name: check file list
          run: cat README.md