name: path-filter
on:
  push:
    paths:
    - '.github/workflows/part1/*'
    - '!.github/workflows/part1/issue.yaml' # 제외 할 경로 

jobs:
    path-filter:
      runs-on: ubuntu-latest
      steps:
      - name: echo hello
        run: echo hello 